### ISSUE TITLE
not able to connect to the openvas,zap,nexpose   i am using ubuntu 16.04

### ISSUE THREAD

**Issue by raghubetageri** [vs4vijay/MultiScanner#25]
python main.py --scan-name sixyfive7 --target http://scanme.nmap.org
[OpenVAS] Not able to connect to the OpenVAS:  (<class 'gvm.errors.RequiredArgument'>, <RequiredArgument message="None">, <traceback object at 0x7f44a94b9308>)
[ZAP] Starting Scan for Target: http://scanme.nmap.org
[ZAP] Starting Scan: sixyfive7
[ZAP] Not able to connect to the ZAP:  (<class 'requests.exceptions.ProxyError'>, ProxyError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://scanme.nmap.org/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f44a94b2518>: Failed to establish a new connection: [Errno 111] Connection refused',)))",),), <traceback object at 0x7f44a945ad08>)
[Nexpose] Starting Scan for Target: http://scanme.nmap.org
[Nexpose] Scan Name: sixyfive7
[Nexpose] Not able to connect to the Nexpose:  (<class 'urllib3.exceptions.MaxRetryError'>, MaxRetryError("HTTPSConnectionPool(host='localhost', port=3780): Max retries exceeded with url: /api/3/sites (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f44a944bb70>: Failed to establish a new connection: [Errno 111] Connection refused',))",), <traceback object at 0x7f44a9471048>)
[OpenVAS] Starting Scan for Target: http://scanme.nmap.org
[OpenVAS] Scan Name: sixyfive7
[OpenVAS] Not able to connect to the OpenVAS:  (<class 'gvm.errors.RequiredArgument'>, <RequiredArgument message="None">, <traceback object at 0x7f44a946ee88>)
╔Scan Status══╦════════╗
║ # ║ Scanner ║ Status ║

**Comment by vs4vijay** [comment]
Hey @raghubetageri, have you setup ZAP, OpenVAS, and Nexpose locally before running the command?

MultiScanner requires mentioned tools installed on machine and configured to it.

**Comment by raghubetageri** [comment]
plz can u mention some download link for ZAP,OpenVAS,Nexpose i m a beginner.......

**Comment by raghubetageri** [comment]
@vs4vijay  NO i wll install and i wl.......
